<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="stylecss.css"?>


<!DOCTYPE CARS[
	<!ELEMENT CARS (CARCATALOG+)>
	<!ELEMENT CARCATALOG (MAKE,MODEL,YEAR,COLOR,ENGINE,NO_OF_DOORS,TRANSMISSION,ACCESSORIES)>
	<!ELEMENT MAKE (#PCDATA)>
	<!ELEMENT MODEL (#PCDATA)>
	<!ELEMENT YEAR (#PCDATA)>
	<!ELEMENT COLOR (#PCDATA)>
	<!ELEMENT ENGINE (NO_OF_CYLINDERS,FUEL)>
	<!ELEMENT NO_OF_CYLINDERS (#PCDATA)>
	<!ELEMENT FUEL (#PCDATA)>
	<!ELEMENT NO_OF_DOORS (#PCDATA)>
	<!ELEMENT TRANSMISSION (#PCDATA)>
	<!ELEMENT ACCESSORIES (#PCDATA)>
	
	<!ATTLIST ACCESSORIES RADIO CDATA #REQUIRED>    
	<!ATTLIST ACCESSORIES AIRCONDITIONING CDATA #REQUIRED>
	<!ATTLIST ACCESSORIES POWER-WINDOWS CDATA #REQUIRED>
	<!ATTLIST ACCESSORIES POWER-STREERING CDATA #REQUIRED>
	<!ATTLIST ACCESSORIES POWER-BREAKS CDATA #REQUIRED>

	<!ENTITY BMW "BMW">
	<!ENTITY ZUSUKI "ZUSUKI">
]>

<CARS>
<CARCATALOG>
	<MAKE>Popular Maker:-&BMW;</MAKE>
	<MODEL>Model:-BMW X3</MODEL>
	<YEAR>Year:-2000</YEAR>
	<COLOR>Color:-BLUE</COLOR>
	<ENGINE>
		NO_OF_CYLINDERS:<NO_OF_CYLINDERS>10 CYLINDERS</NO_OF_CYLINDERS>
		FUEL-Type:<FUEL>MULTI-PORT FUEL INJECTED</FUEL>
	</ENGINE>
	<NO_OF_DOORS>NO_OF_DOORS:-4 DOOR</NO_OF_DOORS>
	<TRANSMISSION>TRANSMISSION-type:-4 SPEED AUTOMATIC</TRANSMISSION>
	<ACCESSORIES RADIO="YES" AIRCONDITIONING="YES" POWER-WINDOWS="NO" POWER-STREERING="YES" POWER-BREAKS="YES"/>
</CARCATALOG>

<CARCATALOG>
	<MAKE>&BMW;</MAKE>
	<MODEL>aaa</MODEL>
	<YEAR>2000</YEAR>
	<COLOR>BLUE</COLOR>
	<ENGINE>
		<NO_OF_CYLINDERS>10 CYLINDERS</NO_OF_CYLINDERS>
		<FUEL>MULTI-PORT FUEL INJECTED</FUEL>
	</ENGINE>
	<NO_OF_DOORS>4 DOOR</NO_OF_DOORS>
	<TRANSMISSION>4 SPEED AUTOMATIC</TRANSMISSION>
	<ACCESSORIES RADIO="YES" AIRCONDITIONING="YES" POWER-WINDOWS="NO" POWER-STREERING="YES" POWER-BREAKS="YES"/>
</CARCATALOG>
</CARS>