<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="styleflight.css"?>

<!DOCTYPE PLANE_FOR_SALE[
	<!ELEMENT PLANE_FOR_SALE (AD+)>
	<!ELEMENT AD (MAKE,MODEL,YEAR,COLOR,DESCRIPTION,PRICE?,SELLER,LOCATION)>
	<!ELEMENT MAKE (#PCDATA)>
	<!ELEMENT MODEL (#PCDATA)>
	<!ELEMENT YEAR (#PCDATA)>
	<!ELEMENT COLOR (#PCDATA)>
	<!ELEMENT DESCRIPTION (#PCDATA)>
	<!ELEMENT PRICE (#PCDATA)>
	<!ELEMENT SELLER (#PCDATA)>
	<!ELEMENT LOCATION (CITY,STATE)>
	<!ELEMENT CITY (#PCDATA)>
	<!ELEMENT STATE (#PCDATA)>	

	<!ATTLIST SELLER PHONE CDATA #REQUIRED>    
	<!ATTLIST SELLER EMAIL CDATA #IMPLIED>

	<!ENTITY C "CESSNA">
	<!ENTITY P "PIPER">
	<!ENTITY B "BEECHCRAFT">
]>

<PLANE_FOR_SALE>
<AD>
	<MAKE>Popular Maker:-&C;</MAKE>
	<MODEL>Model:-aaa</MODEL>
	<YEAR>Year:-2000</YEAR>
	<COLOR>Color:-BLUE</COLOR>
	<DESCRIPTION>DESCRIPTION:-abcd</DESCRIPTION>
	<PRICE>Price:-1509560</PRICE>
	<SELLER PHONE="911057685" EMAIL="Sh@gmail.com">Seller:-hbsdhb</SELLER>
	<LOCATION>
		<CITY>City:-Udupi</CITY>
		<STATE>Karnataka</STATE>
	</LOCATION>
</AD>

<AD>
	<MAKE>Popular Maker:-&P;</MAKE>
	<MODEL>Model:-BBB</MODEL>
	<YEAR>Year:-1860</YEAR>
	<COLOR>Color:-Pink</COLOR>
	<DESCRIPTION>DESCRIPTION:-XCVBN</DESCRIPTION>
	<PRICE>Price:-1509560</PRICE>
	<SELLER PHONE="911057605" EMAIL="Shsss@gmail.com">Seller:-hbsdhb</SELLER>
	<LOCATION>
		<CITY>City:-Udupi</CITY>
		<STATE>Karnataka</STATE>
	</LOCATION>
</AD>

<AD>
	<MAKE>Popular Maker:-&B;</MAKE>
	<MODEL>Model:-CFG</MODEL>
	<YEAR>Year:-1890</YEAR>
	<COLOR>Color:-Pink</COLOR>
	<DESCRIPTION>DESCRIPTION:-XCVBN</DESCRIPTION>
	<PRICE>Price:-1509560</PRICE>
	<SELLER PHONE="911057605" EMAIL="Shsss@gmail.com">Seller:-hbsdhb</SELLER>
	<LOCATION>
		<CITY>City:-Udupi</CITY>
		<STATE>Karnataka</STATE>
	</LOCATION>
</AD>

</PLANE_FOR_SALE>